name: Run Daily Injury Scripts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
  pull_request:
  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl requests beautifulsoup4 aiohttp

      - name: Run scripts
        run: |
          python AFL_Injuries.py
          python Get_player_id.py
          python MLB_Injuries.py
          python NBA_Injuries.py
          python NFL_Injuries.py
          python NRL_injuries.py
          python NHL_Injuries.py
          python Excel_sheet.py
