name: Run Daily Injury Scripts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scripts
      run: |
        python AFL_Injuries.py
        python Get_player_id.py
        python MLB_Injuries.py
        python NBA_Injuries.py
        python NFL_Injuries.py
        python NRL_Injuries.py
        python NHL_Injuries.py
        python Excel_sheet.py
